# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:
  - jekyll-paginate
# Permalinks
permalink:        pretty

# Setup
title:            Renzhi Xing
tagline:          'Renzhi Xing'
description:      'A blog of Renzhi Xing'
url:              https://zora-x93.github.io
baseurl:          /

author:
  name:           'Renzhi Xing'
  url:            https://zora-x93.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/zora-x93/zora-x93.github.io
